\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\bills.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\core\core.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\core\SEQUENCE\globabl_id_seq.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\TABLE\bill.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\TABLE\bill_issuer.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\TABLE\payment.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\CONSTRAINT\pk_bill_id.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\CONSTRAINT\pk_bill_issuer_id.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\CONSTRAINT\pk_payment_id.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\FK_CONSTRAINT\fk_bill_bill_issuer_id.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\FK_CONSTRAINT\fk_payment_bill_id.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\TRIGGER\record_changed_bill.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\TRIGGER\record_changed_bill_issuer.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\TRIGGER\record_changed_payment.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\core\TRIGGER\tf_update_update_time.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\INDEX\fki_payment_bill.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\VIEW\bill_issuer_v.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\VIEW\bill_v.sql
\i C:\Repositories\3PiCreations\KeepTrack\Database\schema\bills\VIEW\unpaid_bill_v.sql
